package com.keyrico.keyrisdk.telemetry

internal enum class TelemetryCodes(val codeName: String) {
    SDK_INIT("sdkInit"),
    GET_TRIGGERED("getTriggered"),
    GET_RESPONSE_HANDLED("getResponseHandled"),
    CONFIRMATION_SCREEN_LAUNCHED("confirmationScreenLaunched"),
    CONFIRMATION_SCREEN_DISMISSED("confirmationScreenDismissed"),
    BROWSER_KEY_DERIVED("browserPublicKeyDerived"),
    KEY_EXCHANGE_SUCCEEDED("keyExchangeSucceeded"),
    PAYLOAD_ENCRYPTED("payloadEncrypted"),
    POST_SENT("postSent"),
    ASSOCIATION_KEY_GENERATED("generateAssociationKey"),
    ASSOCIATION_KEY_GET("getAssociationKey"),
    POST_RESPONSE_RECEIVED("postResponseReceived"),
    ASSOCIATION_KEY_SAVED("associationKeySaved"),
    ASSOCIATION_KEY_QUERIED("associationKeyQueried"),
    ASSOCIATION_KEY_DELETED("associationKeyDeleted"),
    ECDSA_DATA_SIGNED("edcsaDataSigned"),
    ASSOCIATION_KEY_CREATED("associationKeyCreated"),
    ASSOCIATION_KEY_REMOVED("associationKeyRemoved"),
    ON_DATA_CHANGED_FOR_CLOUD_BACKUP("onDataChangedForCloudBackup"),
    PREFS_KEYS_RESTORED("prefsKeysRestored"),
    CHECK_BACKEND_ACCOUNTS_HASH("checkBackendAccountsHash"),
    GET_BACKEND_ACCOUNTS("getBackendAccounts"),
    UPDATE_BACKEND_ACCOUNTS("updateBackendAccounts"),
    SEND_EVENT("sendEvent"),
    EVENT_SENT("eventSent"),
    CREATE_FINGERPRINT("createFingerprint"),
    LOGIN("login"),
    REGISTER("register"),
}
